[package]
name = "compiler_rt"
version = "0.1.0"
edition = "2024_07"  # This must be kept in sync with the `cairo_project.toml` file in the same folder.

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]

[dev-dependencies]
cairo_test = "2.10.1"

[profile.release.cairo]
allow-warnings = false
