use crate::rtstate::RTState;
use crate::alu::uadd_with_overflow::uadd_with_overflow;

pub fn __llvm_uadd_with_overflow_b_b_Sbcs(
    ref state: RTState, lhs: u128, rhs: u128,
) -> (u128, bool) {
    uadd_with_overflow::<u8>(lhs, rhs)
}

#[cfg(test)]
mod tests {
    use crate::rtstate::RTStateOps;
    use super::__llvm_uadd_with_overflow_b_b_Sbcs;
    use crate::alu::test_case::TestCaseTwoArgsTwoExpected;
    #[cairofmt::skip]
    pub const test_cases: [TestCaseTwoArgsTwoExpected; 260] = [
        // Random test cases
        TestCaseTwoArgsTwoExpected{lhs: 1, rhs: 123, expected: (124, false)},
        TestCaseTwoArgsTwoExpected{lhs: 118, rhs: 243, expected: (105, true)},
        TestCaseTwoArgsTwoExpected{lhs: 157, rhs: 70, expected: (227, false)},
        TestCaseTwoArgsTwoExpected{lhs: 88, rhs: 175, expected: (7, true)},
        TestCaseTwoArgsTwoExpected{lhs: 79, rhs: 141, expected: (220, false)},
        TestCaseTwoArgsTwoExpected{lhs: 193, rhs: 216, expected: (153, true)},
        TestCaseTwoArgsTwoExpected{lhs: 40, rhs: 113, expected: (153, false)},
        TestCaseTwoArgsTwoExpected{lhs: 68, rhs: 85, expected: (153, false)},
        TestCaseTwoArgsTwoExpected{lhs: 12, rhs: 10, expected: (22, false)},
        TestCaseTwoArgsTwoExpected{lhs: 120, rhs: 164, expected: (28, true)},
        TestCaseTwoArgsTwoExpected{lhs: 202, rhs: 34, expected: (236, false)},
        TestCaseTwoArgsTwoExpected{lhs: 27, rhs: 48, expected: (75, false)},
        TestCaseTwoArgsTwoExpected{lhs: 192, rhs: 202, expected: (138, true)},
        TestCaseTwoArgsTwoExpected{lhs: 43, rhs: 170, expected: (213, false)},
        TestCaseTwoArgsTwoExpected{lhs: 97, rhs: 39, expected: (136, false)},
        TestCaseTwoArgsTwoExpected{lhs: 93, rhs: 130, expected: (223, false)},
        TestCaseTwoArgsTwoExpected{lhs: 158, rhs: 72, expected: (230, false)},
        TestCaseTwoArgsTwoExpected{lhs: 134, rhs: 3, expected: (137, false)},
        TestCaseTwoArgsTwoExpected{lhs: 219, rhs: 153, expected: (116, true)},
        TestCaseTwoArgsTwoExpected{lhs: 241, rhs: 31, expected: (16, true)},
        TestCaseTwoArgsTwoExpected{lhs: 209, rhs: 101, expected: (54, true)},
        TestCaseTwoArgsTwoExpected{lhs: 179, rhs: 180, expected: (103, true)},
        TestCaseTwoArgsTwoExpected{lhs: 191, rhs: 249, expected: (184, true)},
        TestCaseTwoArgsTwoExpected{lhs: 98, rhs: 39, expected: (137, false)},
        TestCaseTwoArgsTwoExpected{lhs: 53, rhs: 125, expected: (178, false)},
        TestCaseTwoArgsTwoExpected{lhs: 100, rhs: 6, expected: (106, false)},
        TestCaseTwoArgsTwoExpected{lhs: 17, rhs: 140, expected: (157, false)},
        TestCaseTwoArgsTwoExpected{lhs: 119, rhs: 21, expected: (140, false)},
        TestCaseTwoArgsTwoExpected{lhs: 35, rhs: 234, expected: (13, true)},
        TestCaseTwoArgsTwoExpected{lhs: 242, rhs: 23, expected: (9, true)},
        TestCaseTwoArgsTwoExpected{lhs: 34, rhs: 128, expected: (162, false)},
        TestCaseTwoArgsTwoExpected{lhs: 191, rhs: 86, expected: (21, true)},
        TestCaseTwoArgsTwoExpected{lhs: 119, rhs: 61, expected: (180, false)},
        TestCaseTwoArgsTwoExpected{lhs: 171, rhs: 51, expected: (222, false)},
        TestCaseTwoArgsTwoExpected{lhs: 1, rhs: 144, expected: (145, false)},
        TestCaseTwoArgsTwoExpected{lhs: 189, rhs: 73, expected: (6, true)},
        TestCaseTwoArgsTwoExpected{lhs: 45, rhs: 89, expected: (134, false)},
        TestCaseTwoArgsTwoExpected{lhs: 152, rhs: 230, expected: (126, true)},
        TestCaseTwoArgsTwoExpected{lhs: 15, rhs: 134, expected: (149, false)},
        TestCaseTwoArgsTwoExpected{lhs: 63, rhs: 222, expected: (29, true)},
        TestCaseTwoArgsTwoExpected{lhs: 116, rhs: 140, expected: (0, true)},
        TestCaseTwoArgsTwoExpected{lhs: 100, rhs: 245, expected: (89, true)},
        TestCaseTwoArgsTwoExpected{lhs: 52, rhs: 25, expected: (77, false)},
        TestCaseTwoArgsTwoExpected{lhs: 127, rhs: 69, expected: (196, false)},
        TestCaseTwoArgsTwoExpected{lhs: 8, rhs: 137, expected: (145, false)},
        TestCaseTwoArgsTwoExpected{lhs: 115, rhs: 29, expected: (144, false)},
        TestCaseTwoArgsTwoExpected{lhs: 61, rhs: 135, expected: (196, false)},
        TestCaseTwoArgsTwoExpected{lhs: 98, rhs: 67, expected: (165, false)},
        TestCaseTwoArgsTwoExpected{lhs: 36, rhs: 90, expected: (126, false)},
        TestCaseTwoArgsTwoExpected{lhs: 102, rhs: 196, expected: (42, true)},
        TestCaseTwoArgsTwoExpected{lhs: 120, rhs: 161, expected: (25, true)},
        TestCaseTwoArgsTwoExpected{lhs: 78, rhs: 243, expected: (65, true)},
        TestCaseTwoArgsTwoExpected{lhs: 109, rhs: 25, expected: (134, false)},
        TestCaseTwoArgsTwoExpected{lhs: 66, rhs: 98, expected: (164, false)},
        TestCaseTwoArgsTwoExpected{lhs: 186, rhs: 81, expected: (11, true)},
        TestCaseTwoArgsTwoExpected{lhs: 180, rhs: 12, expected: (192, false)},
        TestCaseTwoArgsTwoExpected{lhs: 146, rhs: 105, expected: (251, false)},
        TestCaseTwoArgsTwoExpected{lhs: 134, rhs: 84, expected: (218, false)},
        TestCaseTwoArgsTwoExpected{lhs: 239, rhs: 33, expected: (16, true)},
        TestCaseTwoArgsTwoExpected{lhs: 229, rhs: 71, expected: (44, true)},
        TestCaseTwoArgsTwoExpected{lhs: 121, rhs: 168, expected: (33, true)},
        TestCaseTwoArgsTwoExpected{lhs: 216, rhs: 85, expected: (45, true)},
        TestCaseTwoArgsTwoExpected{lhs: 36, rhs: 48, expected: (84, false)},
        TestCaseTwoArgsTwoExpected{lhs: 16, rhs: 5, expected: (21, false)},
        TestCaseTwoArgsTwoExpected{lhs: 22, rhs: 25, expected: (47, false)},
        TestCaseTwoArgsTwoExpected{lhs: 208, rhs: 121, expected: (73, true)},
        TestCaseTwoArgsTwoExpected{lhs: 133, rhs: 112, expected: (245, false)},
        TestCaseTwoArgsTwoExpected{lhs: 84, rhs: 165, expected: (249, false)},
        TestCaseTwoArgsTwoExpected{lhs: 216, rhs: 146, expected: (106, true)},
        TestCaseTwoArgsTwoExpected{lhs: 185, rhs: 239, expected: (168, true)},
        TestCaseTwoArgsTwoExpected{lhs: 123, rhs: 89, expected: (212, false)},
        TestCaseTwoArgsTwoExpected{lhs: 119, rhs: 18, expected: (137, false)},
        TestCaseTwoArgsTwoExpected{lhs: 93, rhs: 230, expected: (67, true)},
        TestCaseTwoArgsTwoExpected{lhs: 160, rhs: 26, expected: (186, false)},
        TestCaseTwoArgsTwoExpected{lhs: 96, rhs: 105, expected: (201, false)},
        TestCaseTwoArgsTwoExpected{lhs: 218, rhs: 22, expected: (240, false)},
        TestCaseTwoArgsTwoExpected{lhs: 125, rhs: 69, expected: (194, false)},
        TestCaseTwoArgsTwoExpected{lhs: 102, rhs: 108, expected: (210, false)},
        TestCaseTwoArgsTwoExpected{lhs: 95, rhs: 20, expected: (115, false)},
        TestCaseTwoArgsTwoExpected{lhs: 53, rhs: 205, expected: (2, true)},
        TestCaseTwoArgsTwoExpected{lhs: 194, rhs: 175, expected: (113, true)},
        TestCaseTwoArgsTwoExpected{lhs: 145, rhs: 177, expected: (66, true)},
        TestCaseTwoArgsTwoExpected{lhs: 94, rhs: 174, expected: (12, true)},
        TestCaseTwoArgsTwoExpected{lhs: 12, rhs: 73, expected: (85, false)},
        TestCaseTwoArgsTwoExpected{lhs: 220, rhs: 42, expected: (6, true)},
        TestCaseTwoArgsTwoExpected{lhs: 152, rhs: 192, expected: (88, true)},
        TestCaseTwoArgsTwoExpected{lhs: 45, rhs: 43, expected: (88, false)},
        TestCaseTwoArgsTwoExpected{lhs: 197, rhs: 234, expected: (175, true)},
        TestCaseTwoArgsTwoExpected{lhs: 179, rhs: 43, expected: (222, false)},
        TestCaseTwoArgsTwoExpected{lhs: 10, rhs: 208, expected: (218, false)},
        TestCaseTwoArgsTwoExpected{lhs: 0, rhs: 9, expected: (9, false)},
        TestCaseTwoArgsTwoExpected{lhs: 24, rhs: 120, expected: (144, false)},
        TestCaseTwoArgsTwoExpected{lhs: 25, rhs: 175, expected: (200, false)},
        TestCaseTwoArgsTwoExpected{lhs: 107, rhs: 121, expected: (228, false)},
        TestCaseTwoArgsTwoExpected{lhs: 248, rhs: 1, expected: (249, false)},
        TestCaseTwoArgsTwoExpected{lhs: 73, rhs: 73, expected: (146, false)},
        TestCaseTwoArgsTwoExpected{lhs: 208, rhs: 249, expected: (201, true)},
        TestCaseTwoArgsTwoExpected{lhs: 235, rhs: 242, expected: (221, true)},
        TestCaseTwoArgsTwoExpected{lhs: 247, rhs: 140, expected: (131, true)},
        TestCaseTwoArgsTwoExpected{lhs: 221, rhs: 142, expected: (107, true)},
        TestCaseTwoArgsTwoExpected{lhs: 234, rhs: 125, expected: (103, true)},
        TestCaseTwoArgsTwoExpected{lhs: 67, rhs: 214, expected: (25, true)},
        TestCaseTwoArgsTwoExpected{lhs: 225, rhs: 155, expected: (124, true)},
        TestCaseTwoArgsTwoExpected{lhs: 83, rhs: 236, expected: (63, true)},
        TestCaseTwoArgsTwoExpected{lhs: 142, rhs: 105, expected: (247, false)},
        TestCaseTwoArgsTwoExpected{lhs: 50, rhs: 101, expected: (151, false)},
        TestCaseTwoArgsTwoExpected{lhs: 166, rhs: 118, expected: (28, true)},
        TestCaseTwoArgsTwoExpected{lhs: 39, rhs: 111, expected: (150, false)},
        TestCaseTwoArgsTwoExpected{lhs: 184, rhs: 205, expected: (133, true)},
        TestCaseTwoArgsTwoExpected{lhs: 208, rhs: 73, expected: (25, true)},
        TestCaseTwoArgsTwoExpected{lhs: 234, rhs: 32, expected: (10, true)},
        TestCaseTwoArgsTwoExpected{lhs: 53, rhs: 151, expected: (204, false)},
        TestCaseTwoArgsTwoExpected{lhs: 74, rhs: 177, expected: (251, false)},
        TestCaseTwoArgsTwoExpected{lhs: 91, rhs: 62, expected: (153, false)},
        TestCaseTwoArgsTwoExpected{lhs: 46, rhs: 188, expected: (234, false)},
        TestCaseTwoArgsTwoExpected{lhs: 109, rhs: 233, expected: (86, true)},
        TestCaseTwoArgsTwoExpected{lhs: 122, rhs: 7, expected: (129, false)},
        TestCaseTwoArgsTwoExpected{lhs: 202, rhs: 5, expected: (207, false)},
        TestCaseTwoArgsTwoExpected{lhs: 58, rhs: 248, expected: (50, true)},
        TestCaseTwoArgsTwoExpected{lhs: 84, rhs: 115, expected: (199, false)},
        TestCaseTwoArgsTwoExpected{lhs: 167, rhs: 74, expected: (241, false)},
        TestCaseTwoArgsTwoExpected{lhs: 126, rhs: 55, expected: (181, false)},
        TestCaseTwoArgsTwoExpected{lhs: 193, rhs: 104, expected: (41, true)},
        TestCaseTwoArgsTwoExpected{lhs: 9, rhs: 157, expected: (166, false)},
        TestCaseTwoArgsTwoExpected{lhs: 216, rhs: 33, expected: (249, false)},
        TestCaseTwoArgsTwoExpected{lhs: 1, rhs: 122, expected: (123, false)},
        TestCaseTwoArgsTwoExpected{lhs: 139, rhs: 56, expected: (195, false)},
        TestCaseTwoArgsTwoExpected{lhs: 59, rhs: 18, expected: (77, false)},
        TestCaseTwoArgsTwoExpected{lhs: 42, rhs: 92, expected: (134, false)},
        TestCaseTwoArgsTwoExpected{lhs: 209, rhs: 7, expected: (216, false)},
        TestCaseTwoArgsTwoExpected{lhs: 64, rhs: 8, expected: (72, false)},
        TestCaseTwoArgsTwoExpected{lhs: 96, rhs: 203, expected: (43, true)},
        TestCaseTwoArgsTwoExpected{lhs: 57, rhs: 48, expected: (105, false)},
        TestCaseTwoArgsTwoExpected{lhs: 189, rhs: 5, expected: (194, false)},
        TestCaseTwoArgsTwoExpected{lhs: 134, rhs: 116, expected: (250, false)},
        TestCaseTwoArgsTwoExpected{lhs: 92, rhs: 59, expected: (151, false)},
        TestCaseTwoArgsTwoExpected{lhs: 75, rhs: 218, expected: (37, true)},
        TestCaseTwoArgsTwoExpected{lhs: 64, rhs: 146, expected: (210, false)},
        TestCaseTwoArgsTwoExpected{lhs: 127, rhs: 253, expected: (124, true)},
        TestCaseTwoArgsTwoExpected{lhs: 133, rhs: 46, expected: (179, false)},
        TestCaseTwoArgsTwoExpected{lhs: 184, rhs: 65, expected: (249, false)},
        TestCaseTwoArgsTwoExpected{lhs: 91, rhs: 65, expected: (156, false)},
        TestCaseTwoArgsTwoExpected{lhs: 181, rhs: 227, expected: (152, true)},
        TestCaseTwoArgsTwoExpected{lhs: 23, rhs: 107, expected: (130, false)},
        TestCaseTwoArgsTwoExpected{lhs: 170, rhs: 54, expected: (224, false)},
        TestCaseTwoArgsTwoExpected{lhs: 255, rhs: 154, expected: (153, true)},
        TestCaseTwoArgsTwoExpected{lhs: 161, rhs: 77, expected: (238, false)},
        TestCaseTwoArgsTwoExpected{lhs: 112, rhs: 27, expected: (139, false)},
        TestCaseTwoArgsTwoExpected{lhs: 227, rhs: 210, expected: (181, true)},
        TestCaseTwoArgsTwoExpected{lhs: 18, rhs: 223, expected: (241, false)},
        TestCaseTwoArgsTwoExpected{lhs: 135, rhs: 75, expected: (210, false)},
        TestCaseTwoArgsTwoExpected{lhs: 227, rhs: 150, expected: (121, true)},
        TestCaseTwoArgsTwoExpected{lhs: 29, rhs: 84, expected: (113, false)},
        TestCaseTwoArgsTwoExpected{lhs: 101, rhs: 173, expected: (18, true)},
        TestCaseTwoArgsTwoExpected{lhs: 139, rhs: 59, expected: (198, false)},
        TestCaseTwoArgsTwoExpected{lhs: 209, rhs: 16, expected: (225, false)},
        TestCaseTwoArgsTwoExpected{lhs: 169, rhs: 129, expected: (42, true)},
        TestCaseTwoArgsTwoExpected{lhs: 84, rhs: 235, expected: (63, true)},
        TestCaseTwoArgsTwoExpected{lhs: 190, rhs: 77, expected: (11, true)},
        TestCaseTwoArgsTwoExpected{lhs: 249, rhs: 154, expected: (147, true)},
        TestCaseTwoArgsTwoExpected{lhs: 41, rhs: 82, expected: (123, false)},
        TestCaseTwoArgsTwoExpected{lhs: 199, rhs: 37, expected: (236, false)},
        TestCaseTwoArgsTwoExpected{lhs: 34, rhs: 45, expected: (79, false)},
        TestCaseTwoArgsTwoExpected{lhs: 211, rhs: 139, expected: (94, true)},
        TestCaseTwoArgsTwoExpected{lhs: 167, rhs: 17, expected: (184, false)},
        TestCaseTwoArgsTwoExpected{lhs: 201, rhs: 92, expected: (37, true)},
        TestCaseTwoArgsTwoExpected{lhs: 140, rhs: 197, expected: (81, true)},
        TestCaseTwoArgsTwoExpected{lhs: 36, rhs: 139, expected: (175, false)},
        TestCaseTwoArgsTwoExpected{lhs: 51, rhs: 217, expected: (12, true)},
        TestCaseTwoArgsTwoExpected{lhs: 89, rhs: 113, expected: (202, false)},
        TestCaseTwoArgsTwoExpected{lhs: 118, rhs: 102, expected: (220, false)},
        TestCaseTwoArgsTwoExpected{lhs: 17, rhs: 138, expected: (155, false)},
        TestCaseTwoArgsTwoExpected{lhs: 62, rhs: 130, expected: (192, false)},
        TestCaseTwoArgsTwoExpected{lhs: 0, rhs: 136, expected: (136, false)},
        TestCaseTwoArgsTwoExpected{lhs: 153, rhs: 190, expected: (87, true)},
        TestCaseTwoArgsTwoExpected{lhs: 119, rhs: 238, expected: (101, true)},
        TestCaseTwoArgsTwoExpected{lhs: 127, rhs: 150, expected: (21, true)},
        TestCaseTwoArgsTwoExpected{lhs: 24, rhs: 171, expected: (195, false)},
        TestCaseTwoArgsTwoExpected{lhs: 106, rhs: 59, expected: (165, false)},
        TestCaseTwoArgsTwoExpected{lhs: 100, rhs: 199, expected: (43, true)},
        TestCaseTwoArgsTwoExpected{lhs: 93, rhs: 71, expected: (164, false)},
        TestCaseTwoArgsTwoExpected{lhs: 124, rhs: 6, expected: (130, false)},
        TestCaseTwoArgsTwoExpected{lhs: 136, rhs: 191, expected: (71, true)},
        TestCaseTwoArgsTwoExpected{lhs: 17, rhs: 205, expected: (222, false)},
        TestCaseTwoArgsTwoExpected{lhs: 86, rhs: 172, expected: (2, true)},
        TestCaseTwoArgsTwoExpected{lhs: 11, rhs: 254, expected: (9, true)},
        TestCaseTwoArgsTwoExpected{lhs: 252, rhs: 186, expected: (182, true)},
        TestCaseTwoArgsTwoExpected{lhs: 143, rhs: 203, expected: (90, true)},
        TestCaseTwoArgsTwoExpected{lhs: 188, rhs: 135, expected: (67, true)},
        TestCaseTwoArgsTwoExpected{lhs: 69, rhs: 229, expected: (42, true)},
        TestCaseTwoArgsTwoExpected{lhs: 254, rhs: 196, expected: (194, true)},
        TestCaseTwoArgsTwoExpected{lhs: 161, rhs: 77, expected: (238, false)},
        TestCaseTwoArgsTwoExpected{lhs: 65, rhs: 15, expected: (80, false)},
        TestCaseTwoArgsTwoExpected{lhs: 214, rhs: 182, expected: (140, true)},
        TestCaseTwoArgsTwoExpected{lhs: 158, rhs: 157, expected: (59, true)},
        TestCaseTwoArgsTwoExpected{lhs: 189, rhs: 189, expected: (122, true)},
        TestCaseTwoArgsTwoExpected{lhs: 122, rhs: 73, expected: (195, false)},
        TestCaseTwoArgsTwoExpected{lhs: 187, rhs: 123, expected: (54, true)},
        TestCaseTwoArgsTwoExpected{lhs: 112, rhs: 212, expected: (68, true)},
        TestCaseTwoArgsTwoExpected{lhs: 35, rhs: 169, expected: (204, false)},
        TestCaseTwoArgsTwoExpected{lhs: 93, rhs: 182, expected: (19, true)},
        TestCaseTwoArgsTwoExpected{lhs: 135, rhs: 193, expected: (72, true)},
        TestCaseTwoArgsTwoExpected{lhs: 125, rhs: 186, expected: (55, true)},
        TestCaseTwoArgsTwoExpected{lhs: 73, rhs: 218, expected: (35, true)},
        TestCaseTwoArgsTwoExpected{lhs: 180, rhs: 188, expected: (112, true)},
        TestCaseTwoArgsTwoExpected{lhs: 6, rhs: 21, expected: (27, false)},
        TestCaseTwoArgsTwoExpected{lhs: 29, rhs: 206, expected: (235, false)},
        TestCaseTwoArgsTwoExpected{lhs: 153, rhs: 208, expected: (105, true)},
        TestCaseTwoArgsTwoExpected{lhs: 165, rhs: 53, expected: (218, false)},
        TestCaseTwoArgsTwoExpected{lhs: 118, rhs: 168, expected: (30, true)},
        TestCaseTwoArgsTwoExpected{lhs: 64, rhs: 93, expected: (157, false)},
        TestCaseTwoArgsTwoExpected{lhs: 137, rhs: 205, expected: (86, true)},
        TestCaseTwoArgsTwoExpected{lhs: 192, rhs: 249, expected: (185, true)},
        TestCaseTwoArgsTwoExpected{lhs: 43, rhs: 12, expected: (55, false)},
        TestCaseTwoArgsTwoExpected{lhs: 203, rhs: 218, expected: (165, true)},
        TestCaseTwoArgsTwoExpected{lhs: 112, rhs: 16, expected: (128, false)},
        TestCaseTwoArgsTwoExpected{lhs: 53, rhs: 143, expected: (196, false)},
        TestCaseTwoArgsTwoExpected{lhs: 242, rhs: 75, expected: (61, true)},
        TestCaseTwoArgsTwoExpected{lhs: 193, rhs: 122, expected: (59, true)},
        TestCaseTwoArgsTwoExpected{lhs: 181, rhs: 253, expected: (178, true)},
        TestCaseTwoArgsTwoExpected{lhs: 166, rhs: 210, expected: (120, true)},
        TestCaseTwoArgsTwoExpected{lhs: 50, rhs: 44, expected: (94, false)},
        TestCaseTwoArgsTwoExpected{lhs: 192, rhs: 195, expected: (131, true)},
        TestCaseTwoArgsTwoExpected{lhs: 200, rhs: 2, expected: (202, false)},
        TestCaseTwoArgsTwoExpected{lhs: 192, rhs: 8, expected: (200, false)},
        TestCaseTwoArgsTwoExpected{lhs: 6, rhs: 30, expected: (36, false)},
        TestCaseTwoArgsTwoExpected{lhs: 255, rhs: 225, expected: (224, true)},
        TestCaseTwoArgsTwoExpected{lhs: 199, rhs: 113, expected: (56, true)},
        TestCaseTwoArgsTwoExpected{lhs: 254, rhs: 33, expected: (31, true)},
        TestCaseTwoArgsTwoExpected{lhs: 35, rhs: 100, expected: (135, false)},
        TestCaseTwoArgsTwoExpected{lhs: 65, rhs: 221, expected: (30, true)},
        TestCaseTwoArgsTwoExpected{lhs: 78, rhs: 198, expected: (20, true)},
        TestCaseTwoArgsTwoExpected{lhs: 31, rhs: 140, expected: (171, false)},
        TestCaseTwoArgsTwoExpected{lhs: 150, rhs: 155, expected: (49, true)},
        TestCaseTwoArgsTwoExpected{lhs: 208, rhs: 89, expected: (41, true)},
        TestCaseTwoArgsTwoExpected{lhs: 74, rhs: 168, expected: (242, false)},
        TestCaseTwoArgsTwoExpected{lhs: 57, rhs: 138, expected: (195, false)},
        TestCaseTwoArgsTwoExpected{lhs: 60, rhs: 8, expected: (68, false)},
        TestCaseTwoArgsTwoExpected{lhs: 199, rhs: 42, expected: (241, false)},
        TestCaseTwoArgsTwoExpected{lhs: 35, rhs: 19, expected: (54, false)},
        TestCaseTwoArgsTwoExpected{lhs: 204, rhs: 199, expected: (147, true)},
        TestCaseTwoArgsTwoExpected{lhs: 229, rhs: 26, expected: (255, false)},
        TestCaseTwoArgsTwoExpected{lhs: 44, rhs: 122, expected: (166, false)},
        TestCaseTwoArgsTwoExpected{lhs: 235, rhs: 122, expected: (101, true)},
        TestCaseTwoArgsTwoExpected{lhs: 208, rhs: 6, expected: (214, false)},
        TestCaseTwoArgsTwoExpected{lhs: 132, rhs: 222, expected: (98, true)},
        TestCaseTwoArgsTwoExpected{lhs: 12, rhs: 248, expected: (4, true)},
        TestCaseTwoArgsTwoExpected{lhs: 153, rhs: 128, expected: (25, true)},
        TestCaseTwoArgsTwoExpected{lhs: 145, rhs: 36, expected: (181, false)},
        TestCaseTwoArgsTwoExpected{lhs: 163, rhs: 186, expected: (93, true)},
        TestCaseTwoArgsTwoExpected{lhs: 25, rhs: 37, expected: (62, false)},
        TestCaseTwoArgsTwoExpected{lhs: 115, rhs: 220, expected: (79, true)},
        TestCaseTwoArgsTwoExpected{lhs: 234, rhs: 223, expected: (201, true)},
        TestCaseTwoArgsTwoExpected{lhs: 58, rhs: 221, expected: (23, true)},
        TestCaseTwoArgsTwoExpected{lhs: 245, rhs: 118, expected: (107, true)},
        TestCaseTwoArgsTwoExpected{lhs: 72, rhs: 57, expected: (129, false)},

        // Edge cases
        TestCaseTwoArgsTwoExpected{lhs: 0, rhs: 0, expected: (0, false)},
        TestCaseTwoArgsTwoExpected{lhs: 0, rhs: 255, expected: (255, false)},
        TestCaseTwoArgsTwoExpected{lhs: 255, rhs: 0, expected: (255, false)},
        TestCaseTwoArgsTwoExpected{lhs: 255, rhs: 255, expected: (254, true)},
       ];

    #[test]
    fn test_i8() {
        for case in test_cases.span() {
            let mut state = RTStateOps::new();
            assert_eq!(
                __llvm_uadd_with_overflow_b_b_Sbcs(ref state, *case.lhs, *case.rhs), *case.expected,
            );
        }
    }
}
