name: "Cairo CI"
on:
  push:
    branches: ["main"]
    paths:
      - "compiler-rt/**"
  pull_request:
    branches: ["*"]

jobs:
  format-check:
    name: "Check Cairo Formatting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.8.4"
      - run: scarb fmt --check
        working-directory: compiler-rt/

  tests:
    name: "Test Cairo Code"
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.8.4"
      - run: scarb test
        working-directory: compiler-rt/
