# Metadata for the actions workflow
name: "Docs CI"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

# Environment variables that will be set on all runners
env:
  DEV_SHELL: "nix develop '.#ci'"

# Configuration for individual jobs
jobs:
  # This job checks the formatting of the code and other artifacts.
  formatting:
    name: "Check Docs Formatting"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Lix
        shell: bash
        run: |
          curl -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm
      - name: Build Lix Dependencies
        shell: bash
        run: |
          ${{ env.DEV_SHELL }}
      - name: Install Node Deps
        shell: bash
        run: |
          ${{ env.DEV_SHELL }} --command npm install
      - name: Lint Documentation
        shell: bash
        run: |
          ${{ env.DEV_SHELL }} --command npx prettier --check .

  licensing:
    name: "Check Licenses"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: EmbarkStudios/cargo-deny-action@v2.0.4
        with:
          manifest-path: ./Cargo.toml
          command: check
